version: '3'

services:
  db:
    image: mysql:8.0 #ymlにimage:が書かれていて、そのイメージ名がローカルにない場合は、リモートからpullしてくる
    cap_add: 
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: s_alert_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
  web:
    build: .
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && rm -f tmp/sockets/unicorn.sock && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && rm -f tmp/sockets/unicorn.sock && bundle exec unicorn_rails -c /app/config/unicorn.rb -E development -p 3000"
    volumes:
      - .:/app
      # - sock-data:/app/tmp/sockets
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    env_file: 
      - .env
    depends_on:
      - db
#   nginx:
#     build: ./nginx
#     ports:
#       - 80:80
#     volumes: 
#       - sock-data:/app/tmp/sockets
#     restart: always
#     depends_on: 
#       - web
# volumes: 
#   sock-data:
