today = Date.today

User.create!(id: 1, email: 'test@gmail.com', password: 'test5732',last_name: "近藤", first_name: "雅美", last_name_kana: "コンドウ", first_name_kana: "マサミ", company: "里丸印刷", company_form_id: 1, department: "営業部", phone_number: 07065432134, birth_day:"1992-10-13")
User.create!(id: 2, email: 'test2@gmail.com', password: 'test5732',last_name: "道中", first_name: "健", last_name_kana: "ミチナカ", first_name_kana: "タケル", company: "マセキ自動車", company_form_id: 1, department: "営業部",phone_number: 07065432134, birth_day:"1996-11-25")
User.create!(id: 3, email: 'test3@gmail.com', password: 'test5732',last_name: "古謝", first_name: "拳弥", last_name_kana: "コシャ", first_name_kana: "ケンヤ", company: "マセキ自動車", company_form_id: 1, department: "営業部",phone_number: 07065432134, birth_day:"1996-11-25")

Card.create!(id: 1, s_last_name: "上玉利", s_first_name: "猫八", s_last_name_kana: "カミタマリ", s_first_name_kana: "ネコハチ", s_company: "YHM証券", s_company_form_id: 1, s_department: "営業部", s_phone_number: 07065432134, s_birth_day: "1980-10-24", s_hobby_top: "ゴルフ",s_hobby_medium: "釣り", s_hobby_row: "ワイン", user_id: 2)
Card.create!(id: 2, s_last_name: "田中島", s_first_name: "権十郎", s_last_name_kana: "タナカジマ", s_first_name_kana: "ゴンジュウロウ", s_company: "毎日電気", s_company_form_id: 2, s_department: "企画部", s_phone_number: 0706543213, s_birth_day: "1975-11-20", s_hobby_top: "映画", user_id: 1)
Card.create!(id: 3, s_last_name: "高丘", s_first_name: "三之助", s_last_name_kana: "タカオカ", s_first_name_kana: "サンノスケ", s_company: "三十日工業", s_company_form_id: 3, s_department: "開発部", s_phone_number: 07065431234, s_birth_day: "1972-12-15", s_hobby_top: "ビール", s_hobby_medium: "温泉旅行", user_id: 2)
Card.create!(id: 4, s_last_name: "立久井", s_first_name: "琳太郎", s_last_name_kana: "タチクイ", s_first_name_kana: "リンタロウ", s_company: "三十日工業", s_company_form_id: 3, s_department: "営業部", s_phone_number: 07065431234, s_birth_day: "1972-10-15", s_hobby_top: "ゲーム", s_hobby_medium: "温泉旅行", user_id: 1)
Card.create!(id: 5, s_last_name: "金目鯛", s_first_name: "敏夫", s_last_name_kana: "キンメダイ", s_first_name_kana: "トシオ", s_company: "GFY鉄道", s_company_form_id: 2, s_department: "営業部", s_phone_number: 07065431234, s_birth_day: "1972-11-15", s_hobby_top: "野球", s_hobby_medium: "ワイン", s_hobby_row: "犬と遊ぶ", user_id: 2)
Card.create!(id: 6, s_last_name: "熊部", s_first_name: "辰平", s_last_name_kana: "クマベ", s_first_name_kana: "タッペイ", s_company: "小梅販売", s_company_form_id: 1, s_department: "営業部", s_phone_number: 07065431234, s_birth_day: "1989-11-12", s_hobby_top: "ゴルフ", s_hobby_medium: "アニメ鑑賞", user_id: 3)

Record.create!(date: today, phone_time_id: 9, expression_id: 3, phone_call_id: 1, card_id: 6)
Record.create!(date: today.next_day(-15), phone_time_id: 10, expression_id: 1, phone_call_id:1, card_id: 6 )
Record.create!(date: today.next_day(-14), phone_time_id: 18, expression_id: -1, phone_call_id: 1, card_id: 6 )
Record.create!(date: today.next_day(-13), phone_time_id: 17, expression_id: -2, phone_call_id: 1, card_id: 6 ) 
Record.create!(date: today.next_day(-12), phone_time_id: 19, expression_id: 3, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-11), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-10), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-9), phone_time_id: 14, expression_id: 1, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-8), phone_time_id: 18, expression_id: 3, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-7), phone_time_id: 18, expression_id: 1, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-6), phone_time_id: 15, expression_id: -1, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-5), phone_time_id: 12, expression_id: -2, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-4), phone_time_id: 11, expression_id: 3, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-3), phone_time_id: 9, expression_id: -1, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-2), phone_time_id: 17, expression_id: 2, phone_call_id: 1, card_id:6 )
Record.create!(date: today.next_day(-1), phone_time_id: 19, expression_id: 1, phone_call_id: 1, card_id:6 )

Record.create!(date: today, phone_time_id: 9, expression_id: 3, phone_call_id: 1, card_id: 5 )
Record.create!(date: today.next_day(-3), phone_time_id: 10, expression_id: 1, phone_call_id: 2, card_id: 5 )
Record.create!(date: today.next_day(-15), phone_time_id: 18, expression_id: -1, phone_call_id: 1, card_id: 5 )
Record.create!(date: today.next_day(-6), phone_time_id: 17, expression_id: -2, phone_call_id: 1, card_id: 5 ) 
Record.create!(date: today.next_day(-7), phone_time_id: 19, expression_id: 3, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-9), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-2), phone_time_id: 15, expression_id: 2, phone_call_id: 2, card_id:5 )
Record.create!(date: today.next_day(-2), phone_time_id: 14, expression_id: 1, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-7), phone_time_id: 18, expression_id: 3, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-5), phone_time_id: 18, expression_id: 1, phone_call_id: 2, card_id:5 )
Record.create!(date: today.next_day(-12), phone_time_id: 15, expression_id: -1, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-13), phone_time_id: 12, expression_id: -2, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-10), phone_time_id: 11, expression_id: 3, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-8), phone_time_id: 9, expression_id: -1, phone_call_id: 2, card_id:5 )
Record.create!(date: today.next_day(-4), phone_time_id: 17, expression_id: 2, phone_call_id: 1, card_id:5 )
Record.create!(date: today.next_day(-1), phone_time_id: 19, expression_id: 1, phone_call_id: 1, card_id:5 )

Record.create!(date: today.next_day(-1), phone_time_id: 10, expression_id: 1, phone_call_id: 1, card_id: 4 )
Record.create!(date: today.next_day(-2), phone_time_id: 18, expression_id: -1, phone_call_id: 1, card_id: 4 )
Record.create!(date: today.next_day(-3), phone_time_id: 17, expression_id: -2, phone_call_id: 1, card_id: 4 ) 
Record.create!(date: today.next_day(-4), phone_time_id: 19, expression_id: 3, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-5), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-6), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-7), phone_time_id: 14, expression_id: 1, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-8), phone_time_id: 18, expression_id: 3, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-9), phone_time_id: 18, expression_id: 1, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-10), phone_time_id: 15, expression_id: -1, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-11), phone_time_id: 12, expression_id: -2, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-12), phone_time_id: 11, expression_id: 3, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-13), phone_time_id: 9, expression_id: -1, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-14), phone_time_id: 17, expression_id: 2, phone_call_id: 1, card_id:4 )
Record.create!(date: today.next_day(-15), phone_time_id: 19, expression_id: 1, phone_call_id: 1, card_id:4 )


Record.create!(date: today.next_day(-3), phone_time_id: 9, expression_id: 2, phone_call_id: 1, card_id: 3 )
Record.create!(date: today.next_day(-6), phone_time_id:11, expression_id: 2, phone_call_id: 1, card_id: 3 )

Record.create!(date: today.next_day(-15), phone_time_id: 10, expression_id: 1, phone_call_id: 1, card_id: 2 )
Record.create!(date: today.next_day(-14), phone_time_id: 18, expression_id: -1, phone_call_id: 1, card_id: 2 )
Record.create!(date: today.next_day(-13), phone_time_id: 17, expression_id: -2, phone_call_id: 1, card_id: 2 ) 
Record.create!(date: today.next_day(-14), phone_time_id: 19, expression_id: 3, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-9), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-8), phone_time_id: 15, expression_id: 2, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-7), phone_time_id: 14, expression_id: 1, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-5), phone_time_id: 18, expression_id: 3, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-6), phone_time_id: 18, expression_id: 1, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-10), phone_time_id: 15, expression_id: -1, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-11), phone_time_id: 12, expression_id: -2, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-2), phone_time_id: 11, expression_id: 3, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-3), phone_time_id: 9, expression_id: -1, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-4), phone_time_id: 17, expression_id: 2, phone_call_id: 1, card_id:2 )
Record.create!(date: today.next_day(-1), phone_time_id: 19, expression_id: 1, phone_call_id: 1, card_id:2 )

Comment.create!(id:1, text: "この前ゴルフに行ってましたよ", card_id:6, user_id:2 )
Comment.create!(id:2, text: "最近ワインにハマっているそうです", card_id:5, user_id:2 )
Comment.create!(id:3, text: "犬を新しく飼っていました", card_id:5, user_id:3 )
Comment.create!(id:4, text: "アニメが好きだとのことです", card_id:6, user_id:3 )
Comment.create!(id:5, text: "身長が低いのがコンプレックスです", card_id:6, user_id:3 )
Comment.create!(id:6, text: "麻婆豆腐が好らしいです", card_id:4, user_id:2 )
Comment.create!(id:7, text: "ゲームに最近ハマってるそうです", card_id:4, user_id:3 )
Comment.create!(id:8, text: "髪を新しく切っていました", card_id:6, user_id:3 )
Comment.create!(id:9, text: "温泉旅行に行ったそうです", card_id:4, user_id:3 )
Comment.create!(id:10, text: "野球を見に行ったそうです", card_id:5, user_id:2 )

Favorite.create!(id:1, user_id:1, card_id:6)